name: Test main

on:
  push:
    branches: [main]

jobs:
  call-reusable-workflow:
    uses: wlee221/reusable-workflow-poc/.github/workflows/reusable-workflow.yml@main
    with:
      username: wlee221
    secrets:
      EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}
